#!/usr/bin/env bash
#
# apply-recipe.sh — applies com.recipies.yaml.SetupJavaVersionTo25 to a target
# Gradle repo by writing init.gradle into it, running rewriteRun, and cleaning up.
#
# Usage:
#   ./apply-recipe.sh                     # operates on $PWD
#   ./apply-recipe.sh /path/to/target     # operates on the given path
#
# Prerequisite (run once, in this recipes repo):
#   ./gradlew publishToMavenLocal
#
# Compatibility:
#   - macOS / Linux: native bash.
#   - Windows: run inside Git Bash or WSL.

set -euo pipefail

TARGET="${1:-$PWD}"

if [ ! -d "$TARGET" ]; then
  echo "error: target directory does not exist: $TARGET" >&2
  exit 1
fi

if [ ! -x "$TARGET/gradlew" ]; then
  echo "error: $TARGET does not contain an executable gradlew. This script only supports Gradle projects." >&2
  exit 1
fi

INIT_FILE="$TARGET/init.gradle"

if [ -e "$INIT_FILE" ]; then
  echo "error: $INIT_FILE already exists. Refusing to overwrite. Move or delete it and re-run." >&2
  exit 1
fi

cleanup() {
  rm -f "$INIT_FILE"
}
trap cleanup EXIT

cat <<'INIT' > "$INIT_FILE"
// Auto-generated by apply-recipe.sh — do not edit, will be removed on script exit.
initscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'org.openrewrite:plugin:7.23.0'
        classpath 'com.rewrite:openrewrite-custom-recipes:1.0.0'
    }
}

allprojects {
    apply plugin: org.openrewrite.gradle.RewritePlugin

    repositories {
        mavenLocal()
        mavenCentral()
    }

    afterEvaluate {
        if (project.extensions.findByName('rewrite')) {
            rewrite {
                activeRecipe('com.recipies.yaml.SetupJavaVersionTo25')
            }
            dependencies {
                rewrite('com.rewrite:openrewrite-custom-recipes:1.0.0')
            }
        }
    }
}
INIT

echo "==> Running rewriteRun in $TARGET"
(
  cd "$TARGET"
  ./gradlew --init-script init.gradle rewriteRun
)
echo "==> Done. init.gradle has been removed from the target."
